###############################################################
#  Generated by:      Cadence Encounter 11.12-s119_1
#  OS:                Linux x86_64(Host ID khalid.fransg)
#  Generated on:      Mon May 26 14:37:37 2014
#  Design:            mini_mips_p
#  Command:           floorPlan -site CORE -s 629.6 550.0 20.0 20.0 20.0 20....
###############################################################

Version: 8

Head Box: 0.0000 0.0000 787.1950 785.6000
IO Box: 112.0000 112.0000 675.1950 673.6000
Core Box: 112.0000 112.0000 675.1950 673.6000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: CORE 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 CORE 112.0000 112.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_1 CORE 112.0000 114.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_2 CORE 112.0000 117.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_3 CORE 112.0000 119.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_4 CORE 112.0000 122.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_5 CORE 112.0000 125.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_6 CORE 112.0000 127.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_7 CORE 112.0000 130.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_8 CORE 112.0000 132.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_9 CORE 112.0000 135.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_10 CORE 112.0000 138.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_11 CORE 112.0000 140.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_12 CORE 112.0000 143.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_13 CORE 112.0000 145.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_14 CORE 112.0000 148.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_15 CORE 112.0000 151.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_16 CORE 112.0000 153.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_17 CORE 112.0000 156.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_18 CORE 112.0000 158.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_19 CORE 112.0000 161.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_20 CORE 112.0000 164.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_21 CORE 112.0000 166.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_22 CORE 112.0000 169.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_23 CORE 112.0000 171.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_24 CORE 112.0000 174.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_25 CORE 112.0000 177.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_26 CORE 112.0000 179.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_27 CORE 112.0000 182.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_28 CORE 112.0000 184.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_29 CORE 112.0000 187.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_30 CORE 112.0000 190.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_31 CORE 112.0000 192.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_32 CORE 112.0000 195.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_33 CORE 112.0000 197.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_34 CORE 112.0000 200.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_35 CORE 112.0000 203.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_36 CORE 112.0000 205.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_37 CORE 112.0000 208.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_38 CORE 112.0000 210.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_39 CORE 112.0000 213.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_40 CORE 112.0000 216.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_41 CORE 112.0000 218.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_42 CORE 112.0000 221.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_43 CORE 112.0000 223.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_44 CORE 112.0000 226.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_45 CORE 112.0000 229.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_46 CORE 112.0000 231.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_47 CORE 112.0000 234.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_48 CORE 112.0000 236.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_49 CORE 112.0000 239.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_50 CORE 112.0000 242.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_51 CORE 112.0000 244.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_52 CORE 112.0000 247.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_53 CORE 112.0000 249.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_54 CORE 112.0000 252.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_55 CORE 112.0000 255.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_56 CORE 112.0000 257.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_57 CORE 112.0000 260.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_58 CORE 112.0000 262.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_59 CORE 112.0000 265.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_60 CORE 112.0000 268.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_61 CORE 112.0000 270.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_62 CORE 112.0000 273.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_63 CORE 112.0000 275.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_64 CORE 112.0000 278.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_65 CORE 112.0000 281.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_66 CORE 112.0000 283.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_67 CORE 112.0000 286.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_68 CORE 112.0000 288.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_69 CORE 112.0000 291.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_70 CORE 112.0000 294.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_71 CORE 112.0000 296.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_72 CORE 112.0000 299.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_73 CORE 112.0000 301.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_74 CORE 112.0000 304.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_75 CORE 112.0000 307.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_76 CORE 112.0000 309.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_77 CORE 112.0000 312.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_78 CORE 112.0000 314.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_79 CORE 112.0000 317.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_80 CORE 112.0000 320.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_81 CORE 112.0000 322.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_82 CORE 112.0000 325.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_83 CORE 112.0000 327.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_84 CORE 112.0000 330.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_85 CORE 112.0000 333.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_86 CORE 112.0000 335.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_87 CORE 112.0000 338.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_88 CORE 112.0000 340.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_89 CORE 112.0000 343.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_90 CORE 112.0000 346.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_91 CORE 112.0000 348.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_92 CORE 112.0000 351.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_93 CORE 112.0000 353.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_94 CORE 112.0000 356.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_95 CORE 112.0000 359.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_96 CORE 112.0000 361.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_97 CORE 112.0000 364.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_98 CORE 112.0000 366.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_99 CORE 112.0000 369.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_100 CORE 112.0000 372.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_101 CORE 112.0000 374.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_102 CORE 112.0000 377.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_103 CORE 112.0000 379.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_104 CORE 112.0000 382.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_105 CORE 112.0000 385.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_106 CORE 112.0000 387.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_107 CORE 112.0000 390.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_108 CORE 112.0000 392.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_109 CORE 112.0000 395.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_110 CORE 112.0000 398.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_111 CORE 112.0000 400.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_112 CORE 112.0000 403.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_113 CORE 112.0000 405.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_114 CORE 112.0000 408.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_115 CORE 112.0000 411.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_116 CORE 112.0000 413.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_117 CORE 112.0000 416.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_118 CORE 112.0000 418.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_119 CORE 112.0000 421.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_120 CORE 112.0000 424.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_121 CORE 112.0000 426.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_122 CORE 112.0000 429.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_123 CORE 112.0000 431.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_124 CORE 112.0000 434.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_125 CORE 112.0000 437.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_126 CORE 112.0000 439.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_127 CORE 112.0000 442.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_128 CORE 112.0000 444.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_129 CORE 112.0000 447.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_130 CORE 112.0000 450.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_131 CORE 112.0000 452.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_132 CORE 112.0000 455.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_133 CORE 112.0000 457.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_134 CORE 112.0000 460.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_135 CORE 112.0000 463.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_136 CORE 112.0000 465.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_137 CORE 112.0000 468.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_138 CORE 112.0000 470.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_139 CORE 112.0000 473.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_140 CORE 112.0000 476.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_141 CORE 112.0000 478.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_142 CORE 112.0000 481.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_143 CORE 112.0000 483.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_144 CORE 112.0000 486.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_145 CORE 112.0000 489.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_146 CORE 112.0000 491.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_147 CORE 112.0000 494.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_148 CORE 112.0000 496.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_149 CORE 112.0000 499.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_150 CORE 112.0000 502.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_151 CORE 112.0000 504.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_152 CORE 112.0000 507.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_153 CORE 112.0000 509.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_154 CORE 112.0000 512.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_155 CORE 112.0000 515.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_156 CORE 112.0000 517.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_157 CORE 112.0000 520.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_158 CORE 112.0000 522.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_159 CORE 112.0000 525.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_160 CORE 112.0000 528.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_161 CORE 112.0000 530.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_162 CORE 112.0000 533.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_163 CORE 112.0000 535.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_164 CORE 112.0000 538.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_165 CORE 112.0000 541.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_166 CORE 112.0000 543.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_167 CORE 112.0000 546.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_168 CORE 112.0000 548.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_169 CORE 112.0000 551.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_170 CORE 112.0000 554.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_171 CORE 112.0000 556.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_172 CORE 112.0000 559.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_173 CORE 112.0000 561.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_174 CORE 112.0000 564.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_175 CORE 112.0000 567.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_176 CORE 112.0000 569.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_177 CORE 112.0000 572.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_178 CORE 112.0000 574.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_179 CORE 112.0000 577.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_180 CORE 112.0000 580.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_181 CORE 112.0000 582.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_182 CORE 112.0000 585.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_183 CORE 112.0000 587.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_184 CORE 112.0000 590.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_185 CORE 112.0000 593.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_186 CORE 112.0000 595.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_187 CORE 112.0000 598.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_188 CORE 112.0000 600.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_189 CORE 112.0000 603.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_190 CORE 112.0000 606.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_191 CORE 112.0000 608.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_192 CORE 112.0000 611.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_193 CORE 112.0000 613.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_194 CORE 112.0000 616.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_195 CORE 112.0000 619.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_196 CORE 112.0000 621.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_197 CORE 112.0000 624.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_198 CORE 112.0000 626.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_199 CORE 112.0000 629.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_200 CORE 112.0000 632.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_201 CORE 112.0000 634.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_202 CORE 112.0000 637.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_203 CORE 112.0000 639.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_204 CORE 112.0000 642.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_205 CORE 112.0000 645.0000 N 2815 1 0.2000 0.0000
DefRow: ROW_206 CORE 112.0000 647.6000 FS 2815 1 0.2000 0.0000
DefRow: ROW_207 CORE 112.0000 650.2000 N 2815 1 0.2000 0.0000
DefRow: ROW_208 CORE 112.0000 652.8000 FS 2815 1 0.2000 0.0000
DefRow: ROW_209 CORE 112.0000 655.4000 N 2815 1 0.2000 0.0000
DefRow: ROW_210 CORE 112.0000 658.0000 FS 2815 1 0.2000 0.0000
DefRow: ROW_211 CORE 112.0000 660.6000 N 2815 1 0.2000 0.0000
DefRow: ROW_212 CORE 112.0000 663.2000 FS 2815 1 0.2000 0.0000
DefRow: ROW_213 CORE 112.0000 665.8000 N 2815 1 0.2000 0.0000
DefRow: ROW_214 CORE 112.0000 668.4000 FS 2815 1 0.2000 0.0000
DefRow: ROW_215 CORE 112.0000 671.0000 N 2815 1 0.2000 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: Y 0.8000 981 0.8000 1 8
Track: X 7.0000 157 5.0000 1 8
Track: X 0.8000 983 0.8000 1 7
Track: Y 0.8000 981 0.8000 1 7
Track: Y 0.2000 3927 0.2000 1 6
Track: X 0.8000 983 0.8000 1 6
Track: X 0.2000 3935 0.2000 1 5
Track: Y 0.2000 3927 0.2000 1 5
Track: Y 0.2000 3927 0.2000 1 4
Track: X 0.2000 3935 0.2000 1 4
Track: X 0.2000 3935 0.2000 1 3
Track: Y 0.2000 3927 0.2000 1 3
Track: Y 0.2000 3927 0.2000 1 2
Track: X 0.2000 3935 0.2000 1 2
Track: X 0.2000 3935 0.2000 1 1
Track: Y 0.2000 3927 0.2000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 786.2000 2 0.9950
GCellGrid: X 0.2000 394 2.0000
GCellGrid: X 0.0000 2 0.2000
GCellGrid: Y 784.2000 2 1.4000
GCellGrid: Y 0.2000 393 2.0000
GCellGrid: Y 0.0000 2 0.2000

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: GND -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val     #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val >                  #
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr            #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val >                  #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <Partition name="mini_mips_p" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=2 pinSpacingWest=2 pinSpacingSouth=2 pinSpacingEast=2 blockedLayers=0xff >
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes />
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x3

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .mini_mips_p25558.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: out_pad_9 BD2SCARUDQP_1V8_SF_LIN 599.7950 673.6000 N R180 - 01
IO: PVCCo VDDE_ST_SF_LIN 524.3950 673.6000 N R180 - 01
IO: out_pad_8 BD2SCARUDQP_1V8_SF_LIN 448.9950 673.6000 N R180 - 01
IO: PVCCc VDD_ST_SF_LIN 373.6000 673.6000 N R180 - 01
IO: out_pad_7 BD2SCARUDQP_1V8_SF_LIN 298.2000 673.6000 N R180 - 01
IO: PVCCi VDDE_ST_SF_LIN 222.8000 673.6000 N R180 - 01
IO: out_pad_6 BD2SCARUDQP_1V8_SF_LIN 147.4000 673.6000 N R180 - 01
IO: Pcornerur RTCORNERCELL_ST_SF_LIN 675.1950 673.6000 NE R0 - 01
IO: out_pad_5 BD2SCARUDQP_1V8_SF_LIN 0.0000 598.4000 W R270 - 01
IO: out_pad_4 BD2SCARUDQP_1V8_SF_LIN 0.0000 523.2000 W R270 - 01
IO: out_pad_3 BD2SCARUDQP_1V8_SF_LIN 0.0000 448.0000 W R270 - 01
IO: out_pad_2 BD2SCARUDQP_1V8_SF_LIN 0.0000 372.8000 W R270 - 01
IO: out_pad_1 BD2SCARUDQP_1V8_SF_LIN 0.0000 297.6000 W R270 - 01
IO: out_pad_0 BD2SCARUDQP_1V8_SF_LIN 0.0000 222.4000 W R270 - 01
IO: clk_pad_in BD2SCARUDQP_1V8_SF_LIN 0.0000 147.2000 W R270 - 01
IO: Pcornerul LTCORNERCELL_ST_SF_LIN 0.0000 673.6000 NW R0 - 01
IO: PGNDi GNDE_ST_SF_LIN 524.3950 0.0000 S R0 - 01
IO: PGNDc GND_ST_SF_LIN 373.6000 0.0000 S R0 - 01
IO: PGNDo GNDE_ST_SF_LIN 222.8000 0.0000 S R0 - 01
IO: Pcornerll LBCORNERCELL_ST_SF_LIN 0.0000 0.0000 SW R0 - 01
IO: out_pad_15 BD2SCARUDQP_1V8_SF_LIN 675.1950 598.4000 E R90 - 01
IO: out_pad_14 BD2SCARUDQP_1V8_SF_LIN 675.1950 523.2000 E R90 - 01
IO: out_pad_13 BD2SCARUDQP_1V8_SF_LIN 675.1950 448.0000 E R90 - 01
IO: out_pad_12 BD2SCARUDQP_1V8_SF_LIN 675.1950 372.8000 E R90 - 01
IO: out_pad_11 BD2SCARUDQP_1V8_SF_LIN 675.1950 297.6000 E R90 - 01
IO: out_pad_10 BD2SCARUDQP_1V8_SF_LIN 675.1950 222.4000 E R90 - 01
IO: rst_n_pad_in BD2SCARUDQP_1V8_SF_LIN 675.1950 147.2000 E R90 - 01
IO: Pcornerlr RBCORNERCELL_ST_SF_LIN 675.1950 0.0000 SE R0 - 01

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 />...                                  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################


#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="mini_mips_p">
  </Design>
</Properties>

###########################################################$############################################################################################
#  GlobalNetConnection: <net_name> {-pin|-inst|-net} <base_name_pattern> -type {pgpin|net|tiehi|tielo} {-all|-module <name>|-region <box>} [-override] #
########################################################################################################################################################
GlobalNetConnection: VDD -pin VDD -inst PVCCc -type pgpin -all
GlobalNetConnection: GND -pin GND -inst PGNDc -type pgpin -all
GlobalNetConnection: VDD -pin vdd -inst * -type pgpin -all
GlobalNetConnection: VDD -type tiehi -all
GlobalNetConnection: GND -pin gnd -inst * -type pgpin -all
GlobalNetConnection: GND -type tielo -all

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
